# Numpy --> 灵活、快速的多维大型数据集容器

In [2]:
import numpy as np
import pandas as pd

## 创建ndarray数组的四种方式

### 1. 直接将列表转化为ndarray类型

In [3]:
array1 = np.array([12,23,43,35,54,56])

In [4]:
array1

array([12, 23, 43, 35, 54, 56])

### 2. arange

In [5]:
array2 = np.arange(1,100,2)

In [6]:
array2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

### 3. 用linspace方法创建等差数列

In [7]:
array3 = np.linspace(1,10,9)

In [8]:
array3

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

### 4. 使用随机数模块创建

In [9]:
array4 = np.random.randint(1,100,6)

In [10]:
array4

array([30, 25, 71, 14,  5, 83])

## 二维数组创建

### 1. random.randint()

In [11]:
array5 = np.random.randint(1,100,(3,3))

In [12]:
array5

array([[21, 32,  1],
       [98, 96, 97],
       [48, 34, 87]])

### 2. 填充数组  全1/全0数组

In [15]:
array6 = np.ones((4,4))

In [16]:
array6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
array7 = np.zeros((4,4))

In [18]:
array7

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
array8 = np.full((4,4),9)

In [20]:
array8

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

#### 单位矩阵

In [22]:
array9 = np.eye(5)

In [23]:
array9

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 查看数组信息

### 1.数组数据类型

In [24]:
array5.dtype

dtype('int32')

In [25]:
array6.dtype

dtype('float64')

### 2. 数组的元素个数

In [26]:
array5.size

9

### 3.数组形状

In [27]:
array9.shape

(5, 5)

### 4.数组的维度

In [28]:
array1.ndim

1

In [29]:
array9.ndim

2

## 数组的排序、形状调整

### 1. 排序

In [30]:
array1.sort()

In [31]:
array1

array([12, 23, 35, 43, 54, 56])

### 2. 调整形状

In [32]:
array6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
array6.reshape(2,8)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

## 描述性统计信息

### 1. 平均数

In [34]:
array5.mean()

57.111111111111114

In [35]:
array5.mean(axis=0)

array([55.66666667, 54.        , 61.66666667])

### 2. 标准差

In [36]:
array5.std()

35.5416639529329

### 3. 方差

In [37]:
array5.var()

1263.20987654321

## 二维数组的切片

<img src="img.png"/>


In [43]:
array5 [1:4,2:]

array([[97],
       [87]])

## 数组的索引

### 1. ndarray 花式索引

In [44]:
array1

array([12, 23, 35, 43, 54, 56])

In [45]:
array1[[0,2,4]]

array([12, 35, 54])

### 2. 布尔索引

#### 用保存布尔值的数组充当索引 所有true对应的元素对会被选出

In [46]:
array1

array([12, 23, 35, 43, 54, 56])

In [47]:
# 取大于40 的数据
array1>40

array([False, False, False,  True,  True,  True])

In [48]:
array1[array1>40]

array([43, 54, 56])

### 练习

使用布尔索引输出所哟有的偶数

In [49]:
array1[(array1%2)==0]

array([12, 54, 56])

## 数组的运算

In [50]:
array1+2

array([14, 25, 37, 45, 56, 58])

In [51]:
array5**2

array([[ 441, 1024,    1],
       [9604, 9216, 9409],
       [2304, 1156, 7569]])

### 矩阵乘法

In [52]:
arr1 = np.random.randint(1,12,(2,3))
arr2 = np.random.randint(1,12,(3,2))

In [53]:
arr2

array([[ 7,  7],
       [11,  4],
       [ 8,  2]])

In [54]:
arr1

array([[ 4,  5,  8],
       [ 9,  4, 10]])

In [55]:
arr1 @ arr2

array([[147,  64],
       [187,  99]])